name: Update Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Escolha a versão do Python que você utiliza

    - name: Install dependencies
      run: |
        pip install boto3
        pip install awscli

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: arn:aws:iam::386715143968:role/monitoramento-role2
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: us-east-1

    - name: Deploy to AWS Lambda
      run: |
        chmod +x deploy_lambdas.sh
        ./deploy_lambdas.sh
