name: Update Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Escolha a versão do Python que você utiliza

    - name: Install dependencies
      run: |
        pip install boto3
        pip install awscli

    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'sua-região-aws'  # Substitua pela sua região da AWS
      run: |
        cd caminho/para/sua/função  # Substitua pelo caminho da sua função Lambda
        zip -r function.zip .
        aws lambda update-function-code --function-name nome-da-sua-função --zip-file fileb://function.zip --region $AWS_REGION
